### ISSUE TITLE
[Docker 1.12] Cannot update or start

### ISSUE THREAD

**Issue by mvdstam** [DevTable/gantryd#28]
Hi,

When trying to use gantry on a Docker 1.12 server, I get the following:

```
Traceback (most recent call last):
  File "./gantry.py", line 105, in <module>
    run()
  File "./gantry.py", line 87, in run
    result = ACTIONS[action](component)
  File "/opt/gantryd/actions.py", line 25, in update_action
    return component.update()
  File "/opt/gantryd/runtime/component.py", line 94, in update
    container = self.start()
  File "/opt/gantryd/runtime/component.py", line 228, in start
    privileged=self.config.privileged)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 368, in start
    self._raise_for_status(res)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 174, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("{"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}")
```

Any ideas?

CC @josephschorr

**Comment by mvdstam** [comment]
I'm closing this issue because I've fixed it myself. If someone is interested (and if this repo is still active), I'll be willing to update my fork with the necessary changes. Seeing as I'm not a Python developer (and I haven't got the time to properly write unittests for my changes), a PR wouldn't be the way to go in my opinion.

Thanks anyway @josephschorr!

**Comment by josephschorr** [comment]
@mvdstam: Mind creating the PR anyway? If at least so we can get it properly merged.
